{{- $fullname := include "imaginary.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels: {{ include "imaginary.labels" . | nindent 4 }}
spec: {{ if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }} {{ end }}
  selector:
    matchLabels: {{ include "imaginary.selectorLabels" . | nindent 6 }}
  template:
    metadata: {{ with .Values.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }} {{ end }}
      labels: {{ include "imaginary.selectorLabels" . | nindent 8 }}
    spec: {{ with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }} {{ end }} {{ with .Values.persistence }} {{ if .enabled }}
      volumes:
        - name: {{ .path }}
          persistentVolumeClaim:
            claimName: {{ $fullname }} {{ end }} {{ end }}
      serviceAccountName: {{ include "imaginary.serviceAccountName" . }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }} {{ with .Values.persistence }} {{ if .enabled }}
          volumeMounts:
            - mountPath: {{ .path }}
              name: {{ end }} {{ end }}
          args: {{ range .Values.app.args | splitList " " }}
            - {{ . | quote }} {{ end }} {{ if  .Values.persistence.enabled }}
            - "-mount"
            - {{ .Values.persistence.path | quote  }} {{ end }}
            - "-p"
            - {{ .Values.service.containerPort | quote }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.name }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.name }}
          resources: {{ toYaml .Values.resources | nindent 12 }} {{ with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }} {{ end }} {{ with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }} {{ end }} {{ with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }} {{ end }}
