{{- $host := .Values.ingress.host -}}
{{- if $host -}}
{{- $fullName := include "imaginary.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{ include "imaginary.labels" . | nindent 4 }}
  annotations: {{ with .Values.ingress.annotations }} {{ toYaml . | nindent 4 }} {{ end }} {{ with .Values.ingress.uploadSize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ . | quote }} {{ end }} {{ with .Values.ingress.tls }} {{ if .enabled }}
    kubernetes.io/tls-acme: "true" {{ if .issuer.enabled }}
    cert-manager.io/issuer: {{ printf "%s-%s" $.Release.Name .issuer.name }}
    cert-manager.io/common-name: {{ $host }} {{ end }} {{ end }} {{ end }}
spec: {{ with .Values.ingress.className }}
  ingressClassName: {{ . }} {{ end }} {{ with .Values.ingress.tls }} {{ if .enabled }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ $.Values.ingress.secretName | default $host | quote }} {{ end }} {{ end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path  }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.port }} {{ end }}

