apiVersion: v1
kind: Service
metadata:
  name: {{ include "imaginary.fullname" . }}
  labels: {{ include "imaginary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector: {{ include "imaginary.selectorLabels" . | nindent 4 }}
