bases:
  - environment.yaml
---
repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: app-cms
    namespace: '{{ .Values.environment }}'
    chart: '{{ .Values.chart.name }}'
    version: '{{ .Values.chart.version }}'
    labels:
      component: cms
    values:
      - fullnameOverride: '{{ .Values.app.name }}-{{ .Values.app.instance }}'
        image:
          repository: '{{ .Values.imageRepository }}'
          tag: '{{ .Values.imageTag }}'
        serviceAccount:
          name: '{{ .Values.serviceAccount.name }}'
