bases:
  - environment.yaml
---
repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: app-cms
    namespace: {{ .Values.environment }}
    chart: {{ .Values.chart.name }}
    version: {{ .Values.chart.version }}
    labels:
      component: cms
    values:
      - app:
          name: {{ .Values.app.name }}
          instance: {{ .Values.app.instance }}
        replicaCount: {{ .Values.replicaCount }}
        imageRegistry:
          url: {{ .Values.imageRegistry.url }}
        healthcheck:
          host: {{ .Values.app.name }}.{{ .Values.ingress.domain }}
          port: {{ .Values.healthcheck.port }}
          path: {{ .Values.healthcheck.path }}
        serviceAccount:
          name: '{{ .Values.serviceAccount.name }}'
