helmDefaults:
  historyMax: 3
  createNamespace: true
  cleanupOnFail: true
  
helmfiles:
  - path: website.yaml
    values:
      - imageRegistryUrl: '{{ requiredEnv "DOCKER_REGISTRY" }}/{{ requiredEnv "APP_NAME" }}'
        app:
          name: '{{ requiredEnv "APP_NAME" }}'
        
  - path: cms.yaml
    values:
      - imageRegistryUrl: '{{ requiredEnv "DOCKER_REGISTRY" }}/{{ requiredEnv "APP_NAME" }}'
        app:
          name: '{{ requiredEnv "APP_NAME" }}'
         
environments:
  default:
    values:
      - database:
          enabled: false
        tlsIssuer:
          enabled: false
        website:
          name: website
        cms:
          name: cms
  staging:
    values:
      - database:
          enabled: false
        tlsIssuer:
          enabled: true
        website:
          name: website
        cms:
          name: cms
  production:
    values:
      - database:
          enabled: true
        tlsIssuer:
          enabled: true
        website:
          name: website
        cms:
          name: cms
