bases:
  - environment.values.yaml
--- 
repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: app-website
    namespace: '{{ .Values.environment }}'
    chart: bndigital/app
    version: 1.1.4
    labels:
      component: website
    values:
      - fullnameOverride: '{{ .Values.appName }}-website'
        image: '{{ .Values.imageRegistry }}/{{ .Values.appName }}/website:{{ env "GITHUB_SHA" | default "latest" }}'
        serviceAccount:
          name: '{{ .Values.serviceAccountName }}'
        ingress:
          host: '{{ .Values.appName }}.{{ .Values.ingressDomain }}'
          proxy:
            enabled: {{ .Values.ingressBackendEnabled }}
            paths:
              - pathTemplate: strapi
                service:
                  name: {{ .Values.appName }}-cms-app

  - name: app-cms
    namespace: '{{ .Environment.Name }}'
    chart: bndigital/app
    installed: {{ .Values.ingressBackendEnabled }}
    version: 1.1.4
    labels:
      component: cms
    values:
      - fullnameOverride: '{{ .Values.appName }}-cms'
        image: '{{ .Values.imageRegistry }}/{{ .Values.appName }}/cms:{{ env "GITHUB_SHA" | default "latest" }}'
        serviceAccount:
          name: '{{ .Values.serviceAccountName }}'
