bases:
  - defaults.yaml
--- 
repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: app-website
    namespace: {{ .Environment.Name }}
    chart: bndigital/app
    version: 1.1.4
    labels:
      component: website
    values:
      - fullnameOverride: {{ .Values.appName }}-website
        image: {{ .Values.imageRegistry}}/{{ .Values.appName }}/website:{{ .Values.imageTag }}
        serviceAccount:
          name: {{ .Values.serviceAccountName }}
        ingress:
          host: {{ .Values.appName }}.{{ .Values.ingressDomain }}
          proxy:
            enabled: {{ index .Values "ingressBackendEnabled" | default "true" }}
            paths:
              - pathTemplate: strapi
                service:
                  name: {{ .Values.appName }}-cms-app

  - name: app-cms
    namespace: {{ .Environment.Name }}
    chart: bndigital/app
    installed: {{ index .Values "ingressBackendEnabled" | default "true" }}
    version: 1.1.4
    labels:
      component: cms
    values:
      - fullnameOverride: {{ .Values.appName }}-cms
        image: {{ .Values.imageRegistry}}/{{ .Values.appName }}/cms:{{ .Values.imageTag }}
        serviceAccount:
          name: '{{ .Values.serviceAccountName }}'
