helmDefaults:
  historyMax: 3
  createNamespace: true
  cleanupOnFail: true

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io

environments:
  default:
    values:
      - ingressController:
          enabled: false
        tlsIssuer:
          enabled: false
  staging:
    values:
      - ingressController:
          enabled: false
        tlsIssuer:
          enabled: false
  production:
    values:
      - ingressController:
          enabled: true
        tlsIssuer:
          enabled: true

releases:
  - name: ingress-nginx
    namespace: infrastructure
    condition: 'ingressController.enabled'
    chart: ingress-nginx/ingress-nginx
    version: 4.1.0
    labels:
      component: infrastructure
    values:
      - defaultBackend:
          enabled: false
        controller:
          priorityClassName: system-cluster-critical
          ingressClassResource:
            default: true
          config:
            allow-snippet-annotations: 'true'
            enable-modsecurity: 'true'
            use-gzip: 'true'
            use-http2: 'true'
          service:
            omitClusterIP: true
            annotations:
              service.beta.kubernetes.io/do-loadbalancer-name: '{{ requiredEnv "APP_NAME" }}'
              service.beta.kubernetes.io/do-loadbalancer-protocol: 'http2'
              service.beta.kubernetes.io/do-loadbalancer-http2-port: '443'
              service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: 'true'
              service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: 'true'

  - name: cert-manager
    namespace: infrastructure
    chart: jetstack/cert-manager
    condition: 'tlsIssuer.enabled'
    version: v1.8.0
    labels:
      component: infrastructure
    values:
      - installCRDs: true
        metrics:
          prometheus:
            enabled: false
        global:
          priorityClassName: system-cluster-critical
