repositories:
  - name: bndigital
    url: https://bn-digital.github.io/helm

releases:
  - name: '{{ requiredEnv "APP_NAME" }}-website'
    namespace: '{{ env "APP_ENV" | default "default" }}'
    chart: bndigital/app
    version: 2.0.1
    labels:
      component: website
    set:
      - name: app.name
        value: {{ requiredEnv "APP_NAME" }}
      - name: app.component
        value: 'website'
      - name: ingress.host
        value: {{ requiredEnv "DOMAIN" }}
      - name: image.pullPolicy
        value: 'Always'
      - name: image.repository
        value: 'website'
      - name: image.tag
        value: '{{ env "APP_VERSION" | default "latest" }}'
      - name: image.registry.url
        value: '{{ requiredEnv "DOCKER_REGISTRY" }}/{{ requiredEnv "APP_NAME" }}'
      - name: image.registry.username
        value: '{{ requiredEnv "DOCKER_USERNAME" }}'
      - name: image.registry.password
        value: '{{ requiredEnv "DOCKER_PASSWORD" }}'
    values:
      - vcs:
          repository: '{{ env "GITHUB_REPOSITORY" | default "unknown" }}'
          ref: '{{ env "GITHUB_REF_NAME" | default "latest" }}'
          commit: '{{ env "GITHUB_SHA" | default "unknown" }}'
        ingress:
          tls:
            issuer:
              enabled: true
          proxy:
            www: false
            paths:
              - implementation: 'strapi'
                service:
                  name: '{{ .Values.app.name }}-cms-app'
