{{- with $issuer := .Values.ingress.tls.issuer }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name }}
  labels: {{ include "app.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  acme:
    email: {{ printf .email }}
    server: {{ .server }}
    privateKeySecretRef:
      name: {{ .name }}
    solvers:
      - http01:
          ingress:
            class: {{ $.Values.ingress.className }} {{ end }}
