{{- $fullName := include "app.fullname" . -}}
{{- with $issuer := .Values.ingress.tls.issuer }} {{ if .enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name }}
  labels: {{ include "app.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  acme:
    email: {{ printf "%s@%s" "admin" $.Values.ingress.host }}
    server: {{ .server }}
    privateKeySecretRef:
      name: {{ .name }}
    enableDurationFeature: true
    solvers:
      - http01:
          ingress:
            name: {{ $fullName }} {{ end }} {{ end }}
