{{ with .Values.imageRegistry }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" $.Release.Name "registry" }}
  labels: {{ include "app.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .url .username .password (printf "%s@%s" $.Values.app.name .url) (printf "%s:%s" .username .password | b64enc) | b64enc | quote }} {{ end }}
{{ with .Values.app.env }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}
  labels: {{ include "app.labels" $ | nindent 4 }}
data:
  PORT: {{ $.Values.app.port | toString | b64enc | quote }} {{ range $key,$value := . }}
  {{ $key }}: {{ $value | b64enc | quote }} {{ end }} {{ end }}
