{{ with .Values.image.registry }} {{ if and .url .username .password }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "app.registry" $ }}
  labels: {{ include "app.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .url .username .password (printf "%s@%s" $.Values.app.name .url) (printf "%s:%s" .username .password | b64enc) | b64enc | quote }} {{ end }}
---
{{ end }} {{ with .Values.s3 }} {{ if and .enabled .accessKeyId .secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.s3" $ }}
  labels: {{ include "app.labels" $ | nindent 4 }}
data:
  S3_REGION: {{ .region | b64enc | quote }}
  S3_ACCESS_KEY_ID: {{ .accessKeyId | b64enc | quote }}
  S3_SECRET_ACCESS_KEY: {{ .secretAccessKey | b64enc | quote }}
  S3_BUCKET: {{ .bucket | b64enc | quote }}
  S3_PATH: {{ .prefix | b64enc | quote }}
  S3_ENDPOINT: {{ .prefix | b64enc | quote }}
---
{{ end }} {{ end }}
{{ with .Values.app.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}
  labels: {{ include "app.labels" $ | nindent 4 }}
data: {{ range $key,$value := . }}
  {{ $key }}: {{ $value | b64enc | quote }} {{ end }} {{ end }}
