{{ with .Values.serviceAccount }} {{ if .create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" $ }}
  labels: {{ include "app.labels" $ | nindent 4 }} {{ with $.Values.imageRegistry }}
imagePullSecrets:
  - name: {{ printf "%s-%s" $.Release.Name "registry" }} {{ end }} {{ end }} {{ end }}
