{{ with .Values.serviceAccount }} {{ if .create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .name }} {{ .name }} {{ else }} {{ include "app.fullname" $ }} {{ end }}
  labels: {{ include "app.labels" $ | nindent 4 }} {{ with $.Values.image.registry }} {{ if and .url .username .password }}
imagePullSecrets:
  - name: {{ include "app.registry" $ }} {{ end }} {{ end }} {{ end }} {{ end }}
