apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs.fullname" . }}
  labels: {{ include "nodejs.labels" . | nindent 4 }}
data:
  NODE_ENV: 'production'
  PORT: {{ .Values.app.port | quote }}
