apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs.fullname" . }}
  labels: {{ include "nodejs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP {{ with .Values.metrics }} {{ if .enabled }}
    - name: metrics
      port: {{ .port }} {{ end }} {{ end }}
  selector: {{ include "nodejs.selectorLabels" . | nindent 4 }}
