{{- with .Values.database.backup }} {{ if .enabled }}
#file-name: postgresql-backup-cron-job.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgresql-backup-cron-job
spec:
  #Cron Time is set according to server time, ensure server time zone and set accordingly.
  schedule: "@midnight"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgresql-backup-job-pod
              image: 445805446819.dkr.ecr.us-east-2.amazonaws.com/aws-cli-ubuntu:latest
              env:
                - name: S3_BUCKET
                  value: "s3://postgres-backup-11334/dev-pro-cluster/"
                - name: PG_PASS
                  value: "dummy-password"
                - name: AWS_ACCESS_KEY_ID
                  value: "AKIAERTCEER5YERTU8FT-dummy-key"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "VzOerjAN8erv2fEr0E5x+YEER6EKpB/k36oCXlER-dummy-secret"
                - name: AWS_DEFAULT_REGION
                  value: "us-east-2"
                - name: APP_SLACK_WEBHOOK
                  value: "https://hooks.slack.com/services/ER23MER3H/DT5FEDT1E/o1dtysiTdtTBsJbdtEC8DdBJ-dummy-slack-webhook"
              imagePullPolicy: Always
              args:
                - /bin/bash
                - -c
                - cd /home/root; ls; bash postgres-backup.sh;
          restartPolicy: OnFailure
      backoffLimit: 3 {{ end }} {{ end }}
