on:
  workflow_call:
    inputs:
      secrets:
        type: string
        description: Additional key-value map of Value secret paths & names which will be mapped to env variables
        required: false
        default: ''
      environment:
        type: string
        required: false
        default: 'staging'
        deprecationMessage: Environment resolution is now automatic and based on branch type
      version:
        type: string
        required: false
        default: 'latest'
        deprecationMessage: Version resolution is now automatic and based on branch type

env:
  IS_PRODUCTION_ENV: ${{ (github.ref_type == 'tag' && true) || false }}"
  IS_PRIVATE_REPOSITORY: ${{ github.ref_protected }}

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  helm:
    runs-on: ${{ env.IS_PRIVATE_REPOSITORY && 'self-hosted' || 'ubuntu-latest' }}
    env:
      APP_ENV: ${{ (env.IS_PRODUCTION_ENV && 'production') || 'staging' }}"
      APP_NAME: ${{ github.event.repository.name }}
      APP_VERSION: ${{ env.IS_PRODUCTION_ENV && github.ref_name || 'latest' }}
      DOMAIN: ${{ join([github.event.repository.name, 'bndigital.dev'], '.') }}
    environment:
      name: ${{ inputs.environment }}
      url:  ${{ steps.status.outputs.url }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          method: github
          url: ${{ secrets.VAULT_ENDPOINT }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          secrets: |
            infrastructure/data/harbor        registry  | DOCKER_REGISTRY ;
            infrastructure/data/harbor        username  | DOCKER_USERNAME ;
            infrastructure/data/harbor        password  | DOCKER_PASSWORD ;
            infrastructure/data/digitalocean  token     | DIGITALOCEAN_TOKEN ;
            infrastructure/data/kubernetes    cluster   | KUBERNETES_CLUSTER ;
            ${{ inputs.secrets }}

      - name: Setup DigitalOcean cli
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_TOKEN }}

      - name: Configure Kubernetes context
        run: doctl kubernetes cluster kubeconfig save ${{ env.KUBERNETES_CLUSTER }} --set-current-context

      - name: Release Helm charts
        uses: hiberbee/github-action-helm@1.13.0
        env:
          TLS_ENABLED: ${{ env.IS_PRODUCTION_ENV }}
          DATABASE_ENABLED: ${{ env.IS_PRODUCTION_ENV }}
          DATABASE_NAME: ${{ env.APP_NAME }}
        with:
          helmfile: apply
          environment: ${{ env.APP_ENV }}

      - name: Deployment status
        id: status
        run: |
          echo "url=https://${{ env.DOMAIN }}" >> $GITHUB_OUTPUT
