on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: staging
      secrets:
        type: string
        description: Additional key-value map of Value secret paths & names which will be mapped to env variables
        required: false
        default: ''
      version:
        type: string
        required: false
        default: latest

env:
  APP_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  DOMAIN: ${{ github.event.repository.name }}.bndigital.dev
  VAULT_ENDPOINT: ${{ secrets.VAULT_ENDPOINT }}

jobs:
  helm:
    runs-on: self-hosted
    environment:
      name: staging
      url: ${{ env.DOMAIN }}
    env:
      APP_ENV: ${{ inputs.environment }}
      APP_VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Import Vault secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: github
          url: ${{ env.VAULT_ENDPOINT }}
          githubToken: ${{ env.GITHUB_TOKEN }}
          secrets: |
            infrastructure/data/harbor        registry  | DOCKER_REGISTRY ;
            infrastructure/data/harbor        username  | DOCKER_USERNAME ;
            infrastructure/data/harbor        password  | DOCKER_PASSWORD ;
            infrastructure/data/digitalocean  token     | DIGITALOCEAN_TOKEN ;
            infrastructure/data/kubernetes    cluster   | KUBERNETES_CLUSTER ;
            ${{ inputs.secrets }}

      - name: Setup DigitalOcean cli
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_TOKEN }}

      - name: Configure Kubernetes context
        run: doctl kubernetes cluster kubeconfig save ${{ env.KUBERNETES_CLUSTER }} --set-current-context

      - name: Release Helm charts
        uses: hiberbee/github-action-helm@1.13.0
        with:
          helmfile: apply
          environment: ${{ env.APP_ENV }}
