bases:
  - environment.yaml
---
repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: app-website
    namespace: {{ .Values.environment }}
    chart: {{ .Values.chart.name }}
    version: {{ .Values.chart.version }}
    values:
      - fullnameOverride: {{ .Values.app.name }}-{{ .Values.app.instance }}
        app:
          name: {{ .Values.app.name }}
          instance: {{ .Values.app.instance }}
        imageRegistry:
          url: {{ .Values.imageRegistry.url }}
        replicaCount: {{ .Values.replicaCount }}
        serviceAccount:
          name: {{ .Values.serviceAccount.name }}
        healthcheck:
          host: {{ .Values.app.name }}.{{ .Values.ingress.domain }}
          port: {{ .Values.healthcheck.path }}
          path: {{ .Values.healthcheck.path }}
        ingress:
          host: {{ .Values.app.name }}.{{ .Values.ingress.domain }}
          proxy:
            enabled: {{ index .Values "ingress.proxy.enabled" | default "true" }}
            paths:
              - implementation: strapi
                service:
                  name: {{ .Values.app.name }}-cms-app
