bases:
  - environment.yaml
---
repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: app-website
    namespace: {{ .Values.environment }}
    chart: bndigital/app
    version: {{ .Values.chartVersion }}
    values:
      - fullnameOverride: {{ .Values.appName }}-website
        replicaCount: {{ .Values.replicaCount }}
        image: {{ .Values.imageRegistry }}/{{ .Values.appName }}/website:{{ .Values.imageTag }}
        serviceAccount:
          name: {{ .Values.serviceAccountName }}
        ingress:
          host: {{ .Values.appName }}.{{ .Values.ingressDomain }}
          proxy:
            enabled: {{ index .Values "ingressBackendEnabled" | default "true" }}
            paths:
              - pathTemplate: strapi
                service:
                  name: {{ .Values.appName }}-cms-app
