bases:
  - environment.yaml
---
repositories:
  - name: bndigital
    url: https://dcr.bndigital.dev/chartrepo/library

helmDefaults:
  createNamespace: true
  cleanupOnFail: true

releases:
  - name: app-website
    namespace: '{{ .Values.environment }}'
    chart: '{{ .Values.chart.name }}'
    version: '{{ .Values.chart.version }}'
    values:
      - fullnameOverride: '{{ .Values.app.name }}-{{ .Values.app.instance }}'
        image:
          repository: '{{ .Values.imageRepository }}'
          tag: '{{ .Values.imageTag }}'
        serviceAccount:
          name: '{{ .Values.serviceAccount.name }}'
        ingress:
          host: '{{ .Values.app.name }}.{{ .Values.ingress.domain }}'
          proxy:
            paths:
              - implementation: strapi
                service:
                  name: {{ .Values.app.name }}-cms-app
